GO
ALTER TABLE ZONAS ADD ZONADESCRIPCION VARCHAR( 200 ) NULL
GO
-- METODO 1 : INCLUYENDO TODAS LAS COLUMNAS
INSERT INTO ZONAS ( ZONAID, ZONANOMBRE, ZONADESCRIPCION )
			VALUES ( 1, 'NORTE', 'ZONA NORTE DEL ESTADO' )
GO
SELECT * FROM ZONAS
GO
INSERT ZONAS ( ZONADESCRIPCION, ZONAID, ZONANOMBRE )
			VALUES ( 'ZONA SUR DEL ESTADO', 2, 'SUR' )

--METODO 2: OMITIENDO EL NOMBRE DE LAS COLUMNAS ENTONCES ES NECESARIO TODOS LOS VALORES DE LOS CAMPOS
INSERT ZONAS VALUES ( 3, 'ESTE', 'ZONA ESTE DEL ESTADO')

--METODO 3: OMITIR UN CAMPO
INSERT ZONAS ( ZONANOMBRE, ZONAID ) VALUES ( 'NOROESTE', 4 )

--MARCA ERROR, EL CAMPO NOMBRE NO PERMITE NULOS
INSERT ZONAS ( ZONADESCRIPCION, ZONAID ) VALUES ('ZONA NOROESTE DEL PAIS', 5 )

--METODO 4: EN LAS COLUMNAS CON LA PROPIEDAD NULL SE LE PUEDE PASAR EL VALOR NULL
INSERT ZONAS VALUES ( 5, 'ZONA NOROESTE', NULL )

--METODO 5: EN LAS COLUMNAS CON LA PROPIEDAD NOT NULL NO SE LES PUEDE PASAR NULL, MARCA ERROR
INSERT ZONAS VALUES ( 6, NULL, NULL )

SELECT * FROM ZONAS
SELECT * FROM PRUEBA

--INSERTAR A PARTIR DE UNA CONSULTA, SE LE CONOCE COMO INSERCION MASIVA
CREATE TABLE PRUEBA ( CLAVE INT, NOMBRE VARCHAR( 20 ) )

INSERT PRUEBA
SELECT ZONAID, ZONANOMBRE FROM ZONAS

SELECT * FROM PRUEBA
SP_HELP ZONAS

--CREAR UN PROC ALM
CREATE PROC SP_LLENATABLA AS
SELECT ZONAID ZONANOMBRE FROM ZONAS

--EJECUCION
EXEC SP_LLENATABLA

--ELIMINAR REGISTROS EN LA TABLA PRUEBA
DELETE PRUEBA

--UTILIZAR EL SP PARA INSERTAR EN LA TABLA ZONAS
INSERT PRUEBA
EXEC SP_LLENATABLA

SELECT * FROM PRUEBA